name: investra
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  dio: ^5.9.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  file_picker: ^8.0.0+1

  supabase_flutter: ^2.12.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo22.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo22.png"
  adaptive_icon_foreground_inset: 15

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo22.png # نستخدم الرسمة فقط هنا لكي لا تُقص
  android_12:
    image: assets/images/logo22.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DMSerif
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf

    